import Link from 'next/link';

export const metadata = { title: 'Reporting and Privacy Requests' };

export default function ContactPage() {
  return <main className="mx-auto max-w-3xl space-y-6 px-4 py-12 leading-7">
    <h1 className="text-3xl font-bold">Reporting and Privacy Requests</h1>
    <p className="rounded border border-amber-200 bg-amber-50 p-4"><b>Early-access contact:</b> use the temporary email below for support, privacy, removal requests or appeals. This page does not submit a request automatically; send your message from your email app. Formal review procedures and response times are still being established.</p>
    <section><h2 className="text-xl font-bold">Contact VisaThreads</h2><p><a className="break-all text-blue-700 underline" href="mailto:varunchinna5966@gmail.com">varunchinna5966@gmail.com</a></p><p>Include the relevant page link and a short description of your request. Do not send passports, passwords, verification codes, payment details or other sensitive documents. This temporary contact is for the early-access service; it is not an emergency channel.</p></section>
    <section><h2 className="text-xl font-bold">Member content and unwanted messages</h2><p>Signed-in members can use Report on member questions, answers and received messages. In messages, Block prevents further messages in that conversation. Report only the relevant content; do not add extra identity documents. Reporting a private message shares that message with an authorized moderator.</p></section>
    <section><h2 className="text-xl font-bold">Imported content, copyright and privacy</h2><p>The current in-app Report feature does not remove original imported posts or source comments. Email the contact above without creating an account, using “Content removal” or “Copyright request” in the subject. Identify the page, the affected material, your relationship to it and how to reply. Do not publish your request or documents as a public question. Archive removal and future-import suppression still require operator review and an operationally tested process.</p><p>For copyright claims, describe the work and allegedly infringing material, provide contact information, and include the statements of good-faith belief, accuracy and authority and a signature required for a formal notice. A designated DMCA agent has not yet been confirmed; this temporary support contact is not represented as a registered agent.</p></section>
    <section><h2 className="text-xl font-bold">Intimate content shared without consent</h2><p>Use “Urgent intimate-content removal” in the email subject. Include a link or other information locating the material, a way to contact you, your physical or electronic signature, and a statement that you reasonably believe the identified intimate image was published without your consent, with any other relevant information. An authorized representative may contact us. Do not attach, download or forward the image, especially if a child is involved. The operator must maintain the legally required removal and duplicate-review process; staffing and response tracking remain launch requirements.</p></section>
    <section><h2 className="text-xl font-bold">Safety emergencies</h2><p>VisaThreads is not an emergency service. For imminent danger in the U.S., call 911; elsewhere use your local emergency number. Do not download or forward suspected child sexual abuse material. You can report suspected child exploitation to <a className="text-blue-700 underline" href="https://report.cybertip.org/">NCMEC’s CyberTipline</a>. This external reporting option does not replace the operator’s own legal duties.</p></section>
    <section><h2 className="text-xl font-bold">Scams and professional help</h2><p>Check the <a className="text-blue-700 underline" href="https://www.uscis.gov/avoid-scams">USCIS scam-prevention resources</a>. Verify an attorney’s license or a representative’s authorization independently. Never trust a direct message promising guaranteed approval.</p></section>
    <Link href="/community-safety" className="text-blue-700 underline">Back to community safety</Link>
  </main>;
}
