import Link from 'next/link';

export const metadata = { title: 'Terms and conditions — early access' };

export default function TermsPage() {
  return <main className="mx-auto max-w-3xl space-y-6 px-4 py-12 leading-7">
    <h1 className="text-3xl font-bold">Terms and conditions — early access</h1>
    <p>Updated October 6, 2026 · Version 2026-10-06-preview-v2</p>
    <p className="rounded border border-amber-200 bg-amber-50 p-4">These govern the early-access community only and are not finalized production Terms of Service. VisaThreads is the service name; the legal operator, business address and jurisdiction-specific contract review remain unresolved. No agreement to future charges, advertising or a future contract is implied.</p>
    <section><h2 className="text-xl font-bold">Eligibility and your account</h2><p>You must be at least 18 and legally able to agree where you live. Keep credentials and verification codes private, use an email you control, and do not impersonate others or evade restrictions. A verified email does not verify professional qualifications. Review these terms and the privacy notice before affirmatively agreeing.</p></section>
    <section><h2 className="text-xl font-bold">Share experiences responsibly</h2><p>VisaThreads is an independent peer community, not a government website, law firm or verified legal referral service. Do not present guesses as official rules. Cite official sources and dates when possible; accepted answers and topic matches are not legal verification.</p></section>
    <section><h2 className="text-xl font-bold">Do not harm other members</h2><p>No harassment, threats, impersonation, doxxing, scams, sexual exploitation, nonconsensual intimate content, forged documents or instructions to falsify applications. Do not request passports, account credentials, verification codes or payments for guaranteed visa outcomes. Do not evade blocks, suspensions or posting limits.</p></section>
    <section><h2 className="text-xl font-bold">Respect content ownership</h2><p>Publish only material you created or have permission or another lawful basis to share. Do not copy private-group conversations or other people’s identifying documents. Public availability, an API subscription and a source credit do not by themselves grant republication rights. No license to third-party imported material is granted by this website.</p></section>
    <section><h2 className="text-xl font-bold">Recommendations and promotions</h2><p>Disclose employment, payment, referral fees or other material connections when recommending services. Do not publish unsolicited advertisements, fake reviews or misleading claims of professional qualifications. An imported promotional label is a classification, not VisaThreads’s endorsement.</p></section>
    <section><h2 className="text-xl font-bold">Your content and permission to operate</h2><p>You retain ownership of what you submit. You give the operator a nonexclusive, royalty-free permission to host, store, reproduce, display and distribute it only as needed to operate the service, including delivery to recipients you select and safety review. This is not permission to sell private messages or use your identity in advertising. Removal is subject to lawful retention and copies already delivered to others.</p></section>
    <section><h2 className="text-xl font-bold">Reports, removal and appeals</h2><p>Use Report on supported content, Block in a conversation, or the contact channel without an account. Content may be removed and accounts restricted for safety, legal obligations or these rules. A report does not guarantee immediate review or emergency assistance. You may request reconsideration by identifying the decision and explaining your appeal. Repeated copyright infringement can lead to account termination where appropriate.</p><p>Do not download or resend intimate images or suspected child sexual abuse material. Provide a location link and description. A staffed statutory removal process and designated copyright agent where needed remain launch requirements; these terms do not by themselves establish DMCA safe-harbor eligibility.</p></section>
    <section><h2 className="text-xl font-bold">Free preview and future paid services</h2><p>The preview has no paid plans, purchases or advertising integration. Account creation does not authorize a charge. Future pricing, taxes, renewal terms, cancellation, refunds and separate purchase consent must be disclosed before purchase. Existing free accounts will not automatically become paid subscriptions. Sponsored content must be identifiable.</p></section>
    <section><h2 className="text-xl font-bold">Availability, responsibility and leaving</h2><p>The preview can change, contain errors or become unavailable. Verify government rules and deadlines independently; keep your own important records. We do not guarantee accuracy, uninterrupted service or absolute security. Nothing here excludes liability or remedies that cannot lawfully be excluded. These preview terms impose no mandatory arbitration or class-action waiver.</p><p>You may stop using the service, sign out and request account deletion. Sign-out alone does not delete data. Material changes will be versioned and presented for acknowledgement or separate consent where required. Country expansion requires local review; selecting a country page does not change your rights.</p></section>
    <p><Link href="/privacy" className="text-teal-700 underline">Preview privacy notice</Link>{' · '}<Link href="/contact" className="text-teal-700 underline">Reporting and request-channel status</Link></p>
  </main>;
}
