import Link from 'next/link';

export default function CommunitySafetyPage() {
  return <main className="mx-auto max-w-3xl space-y-7 px-4 py-12 leading-7">
    <h1 className="text-3xl font-black">Community safety</h1>
    <section><h2 className="text-xl font-bold">Public questions, pseudonymous accounts</h2><p>Questions and answers are public. A random username hides your name from other members; it does not make your activity untraceable. Your login email is stored by our authentication provider and is not displayed in public profiles.</p></section>
    <section><h2 className="text-xl font-bold">Protect identifying information</h2><p>Do not post passports, application or receipt numbers, SEVIS IDs, addresses, phone numbers, financial records, or other people’s personal information. Text you write can still identify you even when your username does not.</p></section>
    <section><h2 className="text-xl font-bold">Messaging and reports</h2><p>Messages are access-controlled, not end-to-end encrypted. Conversation participants can report individual messages for an authorized moderator to review. Administrators with infrastructure access can also access stored data. Block unwanted conversations and report scams, harassment, spam, or exposed personal information.</p></section>
    <section><h2 className="text-xl font-bold">Experiences are not legal advice</h2><p>This is a peer discussion community, not a government service or a substitute for qualified immigration counsel. An accepted answer reflects the question author’s choice, not professional verification. Verify deadlines and eligibility against current official sources.</p></section>
    <section><h2 className="text-xl font-bold">Community rules</h2><p>No harassment, impersonation, doxxing, unsolicited advertising, document collection, or promises of guaranteed visa outcomes. Posting and messaging limits help reduce abuse. Moderators may remove reported content and suspend accounts.</p></section>
    <section><h2 className="text-xl font-bold">Check official guidance and credentials</h2><p>Use <a className="text-teal-700 underline" href="https://www.uscis.gov/">USCIS</a> and the <a className="text-teal-700 underline" href="https://travel.state.gov/content/travel/en/us-visas.html">U.S. Department of State</a> for current U.S. information. For individual advice, independently verify an attorney’s license or a DOJ-accredited representative’s authorization through a recognized organization. Read <a className="text-teal-700 underline" href="https://www.uscis.gov/avoid-scams">USCIS scam-prevention guidance</a>. A community handle, accepted answer or paid recommendation is not verification.</p></section>
    <section><h2 className="text-xl font-bold">Consent, copyright and serious abuse</h2><p>Do not share copied private discussions, sexual exploitation, nonconsensual intimate material, threats or other people’s documents. Public availability does not establish permission to republish. Disclose any payment or referral relationship when recommending a service. Visit <Link href="/contact" className="text-teal-700 underline">reporting and privacy requests</Link> for available reporting options and the preview’s current limitations.</p></section>
    <section><h2 className="text-xl font-bold">Launch status</h2><p>This preview is still under launch review. The operator’s privacy policy, terms, retention schedule, and support/deletion contact must be finalized before general public signup. This safety page is not a substitute for those policies.</p></section>
    <Link href="/" className="inline-block font-bold text-teal-700 underline">Back to questions</Link>
  </main>;
}
