import Link from 'next/link';

export const metadata = { title: 'Preview privacy notice' };

export default function PrivacyPage() {
  return <main className="mx-auto max-w-3xl space-y-6 px-4 py-12 leading-7">
    <h1 className="text-3xl font-bold">Preview privacy notice</h1>
    <p className="rounded border border-amber-200 bg-amber-50 p-4">Updated September 11, 2026. This describes the current preview, not a finalized production policy. The operator identity, monitored privacy contact, retention periods and applicable rights procedures are still being finalized. Do not submit sensitive information to this preview.</p>
    <section><h2 className="text-xl font-bold">What the app handles</h2><p>Supabase handles login email, password authentication, account identifiers and sessions. The community database stores public pseudonyms, questions, answers, votes, conversations, messages, read status and abuse reports. Cloudflare hosts the website. These providers may process network, device and security logs when you connect.</p></section>
    <section><h2 className="text-xl font-bold">Public and restricted information</h2><p>Questions, replies, public handles and their activity are public. Login email is not included in the app’s public profile views. Message access is restricted by conversation membership; messages are not end-to-end encrypted. Reports disclose the reported content to authorized moderators. Infrastructure administrators can access stored records. Public text and external source links may identify you despite a pseudonym.</p></section>
    <section><h2 className="text-xl font-bold">Why information is processed</h2><p>The app uses these records to authenticate accounts, display discussions and matching topics, deliver conversations, prevent abuse and review reports. Related questions use text and topic matching, not a legal eligibility assessment. The reviewed app does not implement advertising pixels, payments or a marketing mailing list. Provider processing and any future analytics or advertising must be reviewed and disclosed before activation.</p></section>
    <section><h2 className="text-xl font-bold">Browser storage and tracking</h2><p>The login client persists session tokens in browser storage to keep you signed in. Demo mode stores sample activity locally. The reviewed application has no cross-site advertising tracker or application-level Do Not Track / Global Privacy Control preference handler. This is not a claim that providers collect no network data. Any applicable opt-out signals must be implemented before uses requiring them begin.</p></section>
    <section><h2 className="text-xl font-bold">Imported discussions</h2><p>The development archive contains post text and available comments collected through Apify from the configured source. Profile objects and photos are excluded; public handles and some identifying text are replaced or masked. Masking is incomplete and is not full anonymization. Source content is not automatically synchronized or removed when changed on its original site.</p></section>
    <section><h2 className="text-xl font-bold">Retention, deletion and requests</h2><p>There is not yet a self-service export/deletion flow or an approved automatic retention schedule. Logging out does not delete your account, messages or public posts. Backups, security records and legal preservation duties may require separate handling. Production launch requires a working, identity-verified request process and a published retention schedule.</p><Link href="/contact" className="text-teal-700 underline">Current request-channel status</Link></section>
    <section><h2 className="text-xl font-bold">Age and regional requirements</h2><p>The preview is not intended for children. The operator must finalize and implement its age policy before public registration. Privacy rights vary with location and the service’s legal obligations; this preview notice does not waive any rights.</p></section>
    <Link href="/community-safety" className="text-teal-700 underline">Read community safety guidance</Link>
  </main>;
}
