import Link from 'next/link';

export const metadata = { title: 'Preview privacy notice' };

export default function PrivacyPage() {
  return <main className="mx-auto max-w-3xl space-y-6 px-4 py-12 leading-7">
    <h1 className="text-3xl font-bold">Preview privacy notice</h1>
    <p className="rounded border border-amber-200 bg-amber-50 p-4">Updated October 6, 2026. Version 2026-10-06-preview-v2. This describes the current preview, not a finalized production policy. VisaThreads is the service name; the legal operator, business address, retention periods and staffed rights procedures still require confirmation before public launch.</p>
    <section id="collection"><h2 className="text-xl font-bold">Notice before you create an account</h2><p>We process your email address, account identifier and authentication information to create and secure your account. Email signup also asks for your first name and an optional last name. Google sign-in supplies the profile information authorized in its sign-in flow, including your name. Names are stored with your private authentication details; the app publishes only your first-name initial as your avatar, alongside a separately generated public username. Your full name, email and Google photo are not added to public community profiles. We record the policy version you acknowledge, your account ID, a server timestamp, U.S. community context and adult-eligibility confirmation. We do not need your full birth date, passport, Social Security number, immigration case number or payment information to register. Acknowledging this notice is not consent to advertising, a charge or a waiver of privacy rights.</p></section>
    <section><h2 className="text-xl font-bold">What the app handles</h2><p>Supabase handles login email, password authentication, account identifiers and sessions. The community database stores public pseudonyms, questions, answers, votes, conversations, messages, read status and abuse reports. Cloudflare hosts the website. These providers may process network, device and security logs when you connect.</p></section>
    <section><h2 className="text-xl font-bold">Public and restricted information</h2><p>Questions, replies, public handles, first-name avatar initials and their activity are public. Login email and full name are not included in the app’s public profile views. An initial is a display feature, not proof of identity. Message access is restricted by conversation membership; messages are not end-to-end encrypted. Reports disclose the reported content to authorized moderators. Infrastructure administrators can access stored records. Public text, initials and external source links may identify you despite a pseudonym.</p></section>
    <section><h2 className="text-xl font-bold">Why information is processed</h2><p>The app uses these records to authenticate accounts, display discussions and matching topics, deliver conversations, prevent abuse and review reports. Related questions use text and topic matching, not a legal eligibility assessment. The reviewed app does not implement advertising pixels, payments or a marketing mailing list. Provider processing and any future analytics or advertising must be reviewed and disclosed before activation.</p></section>
    <section><h2 className="text-xl font-bold">Browser storage, advertising and sale/sharing</h2><p>The login client persists session tokens in browser storage to keep you signed in. Demo mode stores sample activity locally. Optional analytics, ads, marketing integrations and payments are off. We do not currently sell personal information or share it for cross-context behavioral advertising. Global Privacy Control and Do Not Track do not enable any optional processing. This is not a claim that providers collect no network data or that a future advertising opt-out system is implemented. Future monetization requires review and updated disclosures before activation.</p><Link href="/cookies" className="text-teal-700 underline">Cookies and storage</Link>{' · '}<Link href="/privacy-choices" className="text-teal-700 underline">Your privacy choices</Link></section>
    <section><h2 className="text-xl font-bold">Imported discussions</h2><p>The development archive contains post text and available comments collected through Apify from the configured source. Profile objects and photos are excluded; public handles and some identifying text are replaced or masked. Masking is incomplete and is not full anonymization. Source content is not automatically synchronized or removed when changed on its original site.</p></section>
    <section><h2 className="text-xl font-bold">Retention, deletion and requests</h2><p>There is not yet a self-service export/deletion flow or an approved automatic retention schedule. Logging out does not delete your account, messages or public posts. Backups, security records and legal preservation duties may require separate handling. Production launch requires a working, identity-verified request process and a published retention schedule.</p><Link href="/contact" className="text-teal-700 underline">Current request-channel status</Link></section>
    <section><h2 className="text-xl font-bold">Providers and disclosures</h2><p>In addition to the hosting and database providers above, Resend is configured to deliver account emails; Gmail currently receives support/privacy correspondence. Apify supplied the imported archive. Provider contracts, processing locations and retention settings require review before launch. Information may be disclosed as legally required, to address abuse or protect rights, or in a lawful business transfer subject to applicable safeguards. Selecting a country page does not guarantee that data stays in that country.</p></section>
    <section><h2 className="text-xl font-bold">Sensitive information</h2><p>Do not submit identity documents, credentials, financial details, precise location, medical records or detailed case identifiers. Immigration stories can reveal citizenship, national origin, health or other sensitive information even without a name. We do not offer biometric identification or automated legal-eligibility decisions. Contact us about sensitive information rather than reposting it.</p></section>
    <section><h2 className="text-xl font-bold">U.S. rights and requests</h2><p>Depending on your state and which laws apply, you may have rights to access, correct, delete or obtain a copy of data, opt out of sale/sharing, targeted advertising or certain profiling, limit certain sensitive-data uses, appeal a denial and exercise rights without unlawful discrimination. Authorized agents may submit requests where permitted. Applicable statutory deadlines and exceptions govern; acknowledging this notice does not waive rights.</p><p>Use the temporary contact channel without creating an account. Proportionate identity verification or proof of agent authority may be needed; do not email identity documents unless a safe and necessary process is arranged. Manual request handling, retention and provider-backup procedures still need operational testing.</p><Link href="/privacy-choices" className="text-teal-700 underline">Request instructions and appeals</Link></section>
    <section><h2 className="text-xl font-bold">Age and regional requirements</h2><p>Membership is for adults at least 18 who can legally agree to the terms where they live. Do not register a child. An age checkbox is self-attestation, not proof of age; report suspected child accounts or child personal data through the contact channel. The initial community focuses on the United States. Your residence, citizenship and legal rights are not determined by which country page you choose.</p></section>
    <section><h2 className="text-xl font-bold">Changes and security</h2><p>Material changes will be published under a new policy version with renewed acknowledgement or separate consent where required. Prior acceptance does not authorize unrelated future uses. Access controls and transport security reduce risk but cannot guarantee absolute security.</p><Link href="/contact" className="text-teal-700 underline">Contact VisaThreads</Link></section>
    <Link href="/community-safety" className="text-teal-700 underline">Read community safety guidance</Link>
  </main>;
}
